# Generated by Django 3.0.3 on 2020-05-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200512_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('OutDoor', 'OutDoor'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Furniture', 'Furniture'), ('Gardening', 'Gardening'), ('Kids', 'Kids'), ('Electronics', 'Electronics')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='accounts.Tag'),
        ),
    ]
