# Generated by Django 3.0.3 on 2020-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200512_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Furniture', 'Furniture'), ('Gardening', 'Gardening'), ('Kids', 'Kids'), ('Electronics', 'Electronics')], max_length=255, null=True),
        ),
    ]
